# docker-compose.yml
version: '3.7'

services:
  web:
      build: .
      command: python manage.py runserver  --settings=YemaTest.settings.local 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"