# Generated by Django 3.0.6 on 2020-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20200524_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
    ]
