# Generated by Django 3.0.6 on 2020-05-25 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hospital', models.CharField(max_length=35, verbose_name='Hospital')),
                ('office', models.CharField(max_length=35, verbose_name='Consultorio')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
