# Generated by Django 3.0.6 on 2020-05-25 03:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pediatra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=35, verbose_name='Apellido')),
                ('mother_name', models.CharField(max_length=35, null=True, verbose_name='Apellido Materno')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El formato correcto para es: 5512345678. Hasta 12 digitos.', regex='^\\d{9,12}$')], verbose_name='Numero de Telefono')),
                ('mail', models.EmailField(max_length=254)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
