# Generated by Django 3.0.6 on 2020-05-25 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pediatras', '0002_auto_20200524_2304'),
        ('consultorio', '0002_auto_20200524_2304'),
        ('pacientes', '0003_auto_20200524_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('appointment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Cita')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.Consultorio')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pediatras.Pediatra')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
        ),
    ]
