# Generated by Django 3.0.6 on 2020-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='citas',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Fecha de la Cita'),
        ),
    ]
