# Generated by Django 3.0.6 on 2020-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20200525_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
