# Generated by Django 3.0.6 on 2020-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_citas_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='comment',
            field=models.TextField(default='Sin comentarios'),
            preserve_default=False,
        ),
    ]
