# Generated by Django 3.0.6 on 2020-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20200526_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajes',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='message',
            field=models.TextField(),
        ),
    ]
